### ISSUE TITLE
Passwort authentification broken

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/MyControllerDevice#12]
https://github.com/mycontroller-org/MyControllerDevice/blob/75f2d44eb35e63ac92c6d944ae1a1ede4f78ad6c/MyController.cpp#L388

should read
```
      mqttClient.connect(WiFi.hostname().c_str(), _mqttUser, _mqttPwd);
```

Sadly nobody noticed this ..

**Comment by jkandasa** [comment]
@cimba007 Thank you!
