### ISSUE TITLE
[Wemos] Unable to upgrade firmware

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/MyControllerDevice#2]
Hi i tried to send an update firmware message to my wemos. Apparently, the message didnt get passed to mycontroller library. I think it has got to do with large message sending over mqtt. Any ideas? I already changed the pubsubclient to 512 bytes

**Comment by jkandasa** [comment]
@wengjjpaul what is the memory size of your wemos? 
Very first time you have to write `MyControllerDevice` firmware on your wemos via computer.

**Comment by wengjjpaul** [comment]
this should be the one https://www.wemos.cc/product/d1-mini-pro.html
What do you mean MyControllerDevice firmware? I uploaded a bin file to MyControllerDevice server through the web

**Comment by jkandasa** [comment]
@wengjjpaul looks like you have enough memory.
Ok, once you updated your firmware other functions are working as expected? Like node registered on `MyController` server?

**Comment by wengjjpaul** [comment]
@jkandasa Firmware can be uploaded through serial. Everything works fine like node registration. Only when i want to upload firmware through web, it failed. I checked the mqtt message it is sent out from the server but not received on the node.

**Comment by jkandasa** [comment]
@wengjjpaul Can you check `Resource Log` on server? I will show if you receive any error from your node.

**Comment by wengjjpaul** [comment]
@jkandasa nothing on the resource log

**Comment by wengjjpaul** [comment]
@jkandasa how do you build a firmware for mycontrollerserver?

**Comment by jkandasa** [comment]
@wengjjpaul Can you come on gitter chat? https://gitter.im/mycontroller-org/mycontroller

**Comment by wengjjpaul** [comment]
Issue resolved by editing `PubSubClient.h`

```
// MQTT_MAX_PACKET_SIZE : Maximum packet size
#ifndef MQTT_MAX_PACKET_SIZE
#define MQTT_MAX_PACKET_SIZE 512
#endif
```
