### ISSUE TITLE
Wrong mqtt server input

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/MyControllerDevice#3]
If I key in a wrong mqtt server to the Arduino, the Arduino gets stucked searching for mqtt server. Is there anyway to fix this? I had to clear ROM to rehost hotspot

**Comment by jkandasa** [comment]
@wengjjpaul You have to assign `FACTORY_RESET_PIN` on https://github.com/mycontroller-org/MyControllerDevice/blob/master/McConfig.h#L30 and hold this button to `0` for 9 seconds.

**Comment by wengjjpaul** [comment]
@jkandasa I see. Thank you for the info!

**Comment by jkandasa** [comment]
@wengjjpaul Does this info helps?

**Comment by wengjjpaul** [comment]
Yes. Thank you

**Comment by jkandasa** [comment]
Thanks. I will close this issue.
