### ISSUE TITLE
Auto discovery only once

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/MyControllerDevice#4]
Thanks for implementing Auto discovery of mqtt server using mdns. I tried it, its working good. But i noticed when it finds the mqtt server, it stores the ip. If the server changes ip, it does not rediscover. It keep trying to connect to the old discovered server. Is it possible to make it such that if it is not able to find the old server, do another discovery?

**Comment by jkandasa** [comment]
@wengjjpaul Can you give a try with recent code?
