### ISSUE TITLE
MyController::initialize()  for Wemos D1 mini fails

### ISSUE THREAD

**Issue by njbuch** [mycontroller-org/MyControllerDevice#5]
The device code works fine with some ESP8266 boards, but the Wemos D1 Mini board fails.

The culprit is the strcpy(nodeEui, WiFi.hostname().c_str()); line 89 of MyController.cpp, and I suspect the underlying libraries might have different behaviour in regards to the hostname field.

Not sure though.

**Comment by jkandasa** [comment]
@njbuch can you replace this line with some string and check it?

```
strcpy(nodeEui, "my-node-xyz");
```

**Comment by njbuch** [comment]
It seems that enabling the factory reset, in the McConfig.h and the doing the factory reset, actually solved the problem. I guess it had something to do with weird configuration data somewhere in flash.

Closing.
