### ISSUE TITLE
AP Name is not initialised

### ISSUE THREAD

**Issue by Stephan35** [mycontroller-org/MyControllerDevice#6]
Hello ,
i use a ESP8266 - ESP12f
Old AP appear (of my old programm) so where should i change value of it ?
Thanks

**Comment by jkandasa** [comment]
@Stephan35 First time you have to upload this code to your ESP via serial port.

If you have already uploaded this code. connect with your AP(default password: `mycontroller`) and on your browser launch IP http://192.168.4.1

**Comment by Stephan35** [comment]
thanks, i make a mistake with password, 8 char minimum !!!
Sorry for disturbing , i have to  RTFM ;-)
Now ESP have ESP_XXXX AP name .
